spring:
  application:
    name: aperture

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/aperture_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: 8080

aperture:
  storage:
    root: ${APERTURE_STORAGE_ROOT:storage}
